#!/bin/sh
#
# script to run aide --check and verify GPG signatures
#
# written by Vincent Danen <vdanen-at-annvix.org>
#
# $Id$

# variables
version="@pkg_version@"
hostname=`uname -n`
gpg="/usr/bin/gpg"
aide="/usr/sbin/aide"
fname="aide-`hostname`-`date +%Y%m%d-%H%M%S`"
header="AIDE+gpg - GnuPG authenticity for AIDE databases\nversion: ${version} - \$Id$\n\n"

# get the database directory
dbdir=$(egrep '^@@define DBDIR' /etc/aide.conf | awk '{print $3}')
database_file=$(egrep '^database=' /etc/aide.conf | sed "s|file:@@{DBDIR}|${dbdir}|g" | cut -d '=' -f 2)
databasenew_file=$(egrep '^database_out=' /etc/aide.conf | sed "s|file:@@{DBDIR}|${dbdir}|g" | cut -d '=' -f 2)

export GNUPGHOME=/root/.gnupg

echo "AIDE+gpg integrity check for ${hostname} beginning (`date`)"
echo ""
if [ ! -e ${database_file} ] ; then
    echo "**** Error: AIDE database for ${hostname} not found."
    echo "**** Run 'aideinit' to create the database file."
else
    if [ -f /etc/aide.conf ]; then
        if [ -f ${database_file}.sig ]; then
	    pushd ${dbdir} >/dev/null
	        echo "Verifying the GPG signature on the database..."
		echo ""
	        ${gpg} --verify ${database_file}.sig
		echo ""
		if [ "$?" == "1" ]; then
		    echo "************************************************************"
		    echo "GPG signature FAILED!  Your database has been tampered with!"
		    echo "************************************************************"
		    exit 1
		fi
	    popd >/dev/null
	else
	    echo "**** Error: No GPG signature found for the AIDE database!"
	    echo "**** Unable to verify database; your system may be compromised or incorrectly configured!"
	    exit 1
	fi
        nice -20 ${aide} --check -B "report_url=file:/var/lib/aide/reports/${fname}.report" 2>/dev/null
    fi
fi

exit 0
